// Custom shader file for wutever-rox.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

wutever-rox/26C1247B5DA84F0F02E32B3857130107
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0000.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/E1BB0C779487F8C59D4DF5C5F9B3ADBB
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0001.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/D0349EF0E8F11BC80621580A22F5BB5B
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0027.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/1B91ED55326843F4D3E80A6D6B35A789
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0002.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/8A75526B24843238BD2529508FE3A0CA
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0026.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/D5732DB11A9A11362FCD4A854A6D61AF
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0023.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/B54BA24BA533716AE9863C44B1E76BE1
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0025.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/6995C1CC05ADBC00522D53DA12C5D552
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0021.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/141523E0EA1A70A9DDA38CA67E6C8AE1
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0009.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/02C8310D6FD9874EAD05F580C8EB0B48
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0005.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/3B3DFA50E07C21E05075FCCDDEE101A0
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0028.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/499CDF230FC7846B7239DEED1F83CB16
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0018.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/A759B0D5B86CD8655909A60AED3FC3D1
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0030.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/B9F55B3CC241DE0D150C7933EE27B329
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0022.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/9B0A87BB744A02B992C464E068557614
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0008.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/3DB58CE59DD756BAAF0BEA01B758A39A
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0015.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/B1FDB5411BA708A130FF4B85B7A1EE3B
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0031.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/9F4B3A6CC1868165DF835C5357DE3A87
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0012.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/ED5D083A0424F5BB1F347C51B0EAF086
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0014.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/AD5B47509D21E519D3645DD98F8ED908
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0006.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/B84BDF958ACD011C943316436B8D143F
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0017.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/74399271B50B5947862BDE601678BE3A
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0020.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/ED92BF89DDB58639824DEB501F0127F1
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0016.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/E0543DD01DF8C79EEDF91F05A90A11F4
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0011.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/291C512B704D9FDD53C96C505BA34D90
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0024.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/FE9A92496DE37B1437D937AAA8EAB753
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0004.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/E61E3CA87EE64F01526D03D86F848062
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0003.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/1A619F2F417E9A844B4DAEF8398062F5
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0010.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/27BCA2A707B858B8F0BBAA047A00B9BA
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0013.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/567EE12A3F9BDCFE9046C30EBF088E8C
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0029.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/57F2AA076FC61C4B2F657E20F282FFDB
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0019.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/62CADEAA5221F63B792A7B1A7F706A99
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0007.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/FCDB00FF8A1E6E9A508F47F2F950B43E
{
	q3map_lightmapSize 512 512
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0032.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/old-brick.tga
		blendFunc filter
	}
}

wutever-rox/DAA4523A7EE09F3B94635EA7B7F9394E
{
	q3map_lightmapSize 1024 1024
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0033.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/road01#.tga
		blendFunc filter
	}
}

wutever-rox/DBCF7497D2919010CF4DD6DABC61012D
{
	q3map_lightmapSize 1024 1024
	q3map_lightmapBrightness 2.2
	{
		tcgen lightmap
		map maps/wutever-rox/lm_0034.tga
		rgbGen identityLighting
	}
	{
		map textures/wutever/road01#.tga
		blendFunc filter
	}
}

